### ISSUE TITLE
Integration with new To-Do list feature in HA 2023.11.0

### ISSUE THREAD

**Issue by WhimsySpoon** [ScottG489/ha-trello#3]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/scottg489/ha-trello/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Home Assistant added a new To-Do list feature in HA Core 2023.11.0.

### Describe the solution you'd like

Can this integration support the new To-Do list integration similar to the core integration for Todoist and Google Tasks?

### Describe alternatives you've considered

Moving to using Google Tasks instead of Trello

### Additional context

None.

**Comment by ScottG489** [comment]
Hey @WhimsySpoon! Thanks for using my integration :) Yes, this is a great idea and definitely something I've thought about.

I think there are a few decisions to be made because Trello doesn't quite fit the model of a traditional to-do list. It allows users to choose different workflows for how to manage their tasks.

For instance, a user could have a workflow where they move a card from one list to a "Done" list when a task is completed. Another could put due dates on cards and mark them as complete to consider it done. Or there could be a completely different workflow I haven't considered.

**Could you tell me how you use Trello and how you imagine this working in Home Assistant?**

Getting feedback from users who'd like to use Trello as a to-do list in HA would really help me figure out the best way to implement this :) Looking forward to hearing your thoughts!

<hr/>

Edit: *Sorry, accidentally checked and unchecked a checkbox in your comment.*

**Comment by WhimsySpoon** [comment]
@ScottG489 first of all, thank you for your time and efforts in this component. I've been using it for a few days now and it's been very helpful and rock-solid!

My partner and I have a number of Trello boards that we use for organisation - effectively one board per category. We have one for things do to around the home, such as replacing a failed lightbulb, booking the car in for a service, garden maintenance and other boards for things like vacation planning, big stand-alone projects like renovations etc.

My personal interest is to have the first board, the "Home" board included in the HA To-do integration. This is a simple board with three lists: "To-do", "In Progress" and "Complete". We've been using it for about a year and the "In Progress" list is seldom used. Long-running actions used to live in here, but we tend to put cards from To-Do straight to Completed.

Following a naming convention such as this should facilitate and integration with the HA To-do list functionality

**Comment by ScottG489** [comment]
Really great to hear it's been working well for you!

So it sounds like you're using an entire board as a to-do list. Where each card in the "To-do" (or "In Progress" when used) Trello list would correspond to a HA to-do list item and it being in the "Complete" column would constitute it being mrked complete. Am I understanding that correctly?

One solution here could be to map user's boards to to-do lists in HA. The to-do list would have all the cards on that board. When a card is moved to a "Done" or "Complete" list we could mark that item as complete in the HA to-do list. We would probably allow users to configure which list is considered the "done" list as well.

However, I can imagine other workflows where users have multiple lists on a board and would want separate to-do lists for each Trello list or something along those lines, so I'm a little hesitant to start an implementation that locks into one particular workflow. On the other hand, it does seem like your workflow is probably the most common for using Trello as a to-do list (very similar to how I've used it in the past as well).

What are your thoughts on this potential implementation?

**Comment by WhimsySpoon** [comment]
> Am I understanding that correctly?

100% correct.

My background of using Trello comes from using it as a Kanban board in a software engineering environment. Originally I had multiple lists more akin to Kanban, but Kanban and my partner were not compatible, so we now have a two column Kanban board of to do and done.

We've been using this for about four years and our Completed column is now longer than a Leonard Cohen song. It doesn't really serve a purpose as we've not once had a situation where we wanted to look at the Completed list for something we've done in the past. 

I keep thinking about deprecating the completed list and just having a single to do list where the cards get archived once complete (which would be easy to implement here). That though trail then leads me onto thinking about moving away to something more native to HA, but I love the flexibility trello's card description gives you. 

Apologies, not a straight forward answer, but this is probably because of trying to fit a square peg into a round hole.

**Comment by ScottG489** [comment]
Haha same. My "Done" list is huge, but I've never really gone and looked at old cards either.

That's a good point about archived cards as well. That's another potential workflow someone could follow.

Otherwise, I think I'm leaning towards what I mentioned earlier. I'll map boards to HA to-do lists with cards mapping to tasks and mapping their completed status in HA to whether they're in a user configurable "done" column in Trello. That seems like a common enough workflow that it should work for most people.

This project doesn't have too many users now, so I'd like to grow the features and can just adapt to different workflows as people find the project rather than waiting for feedback otherwise.

I'll take a look at the to-do implementation in HA and see what this would look like and try to prototype something. I also have a long standing PR to merge into core (hoping to evolve this project faster and keep core more stable) that has some issues that need to be addressed which I'm working on.

Will keep this issue updated with my to-do progress shortly :)

**Comment by WhimsySpoon** [comment]
Thanks @ScottG489. I'll help wherever I can with testing. More than happy to play with betas etc.

**Comment by ScottG489** [comment]
Just a small update here to let you know I haven't forgotten about this. I've had a busy month so haven't been able to work on things as much as I'd hoped, but the work for the core PR is mostly done, so I should be able to focus on this next!

**Comment by WhimsySpoon** [comment]
No need to explain; life comes first!

**Comment by TomKranenburg** [comment]
Really hype about what you're doing @ScottG489. I was shocked there is no Trello integration for HA. I know my way around the API quite well at this point so it is possible. You can integrate anything with Trello really.

**Comment by ScottG489** [comment]
Thanks @TomKranenburg, that really means a lot to hear :)

Yes, Trello's API is quite nice! Lots of stuff I'm still looking forward to implementing. Feel free to post any issues for features you'd be interested in using!

My core PR is still in the works and I'm holding myself to finish that before adding things here. But after that I plan on using this project to add new features before core so things can move more quickly.

**Comment by TomKranenburg** [comment]
> Thanks @TomKranenburg, that really means a lot to hear :)
> 
> Yes, Trello's API is quite nice! Lots of stuff I'm still looking forward to implementing. Feel free to post any issues for features you'd be interested in using!
> 
> My core PR is still in the works and I'm holding myself to finish that before adding things here. But after that I plan on using this project to add new features before core so things can move more quickly.

Very mature decision Scott. We'll see how my work load is at my job then I'll help you if possible. Like I said as far as APIs go Trellos is pretty robust. I don't foresee any major issues(famous last words).

If you need someone to do some testing I can volunteer for that at least at the moment. Just drop me a message.
